
import pathlib
import sys

import nametable_builder 

"""
This script has been generated by nametable_builder.py.  It's intended to rebuild the nametable
into a .bin

Unless modified, it will reproduce the original.  
"""

file = pathlib.Path(__file__)
output = file.parent / file.name.replace(".py", ".bin")

original_sha1sum = "451fa63151ac42942eb7161e7d8546f4c15f97cd"

characters = (
    #0123456789ABCDEF
    "0123456789ABCDEF" #0
    "GHIJKLMNOPQRSTUV" #1
    "WXYZ-,'>!♡abcdef" #2
    "ghijklmnopqrstuv" #3
    "wxyz#$%&'()*+/:;" #4
    "<=?@[]^_`{|}~¹º»" #5
    "¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊË" #6
    "ÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛ" #7
    "ÜÝÞßàáâãäåæçèéêë" #8
    "ìíîïðñòóôõö÷øùúû" #9
    "üýþÿЉЊЋЌЍЎЏАБВГД" #A
    "ЕЖЗИЙКЛМНОПРСТУФ" #B
    "ХЦЧШЩЪЫЬЭЮЯабвгд" #C
    "εζηθικλμνξοπρςστ" #D
    "υφχψωϊϋόύώϏϐϑϒϓϔ" #E
    "ϕϖϗϘϙϚϛϜϝϞϟϠϡͰͱ " #F
)  # fmt: skip

table = """
ÎÞ¾¾¾ÜíÜzß¾Î¼½ÞìßÎìÝßÞ¾Þ¾Î¾ÜÝÝßÎ
ÎÜyÎüíÎ¾ÞÜyÞÌÍÜýÜýÞÜÝíÎÜyÎwßìßÜý
Þ¾ÞüßÞÞüÝßÞoppppppppqÞüßÞÞÞÜýìß¾
Üxßopppppppr  -TYPE spppppppqÎìý
¾Üír       tuuuuuuuuv       sÞÞ¾
y¾Îr                        sÜÝý
ÞÎÞr                        sìßÜ
¾üßr     CONGRATULATIONS    sÎ¼½
wß¾r                        sÞÌÍ
ÞÜyr                        sÜíÜ
¼½Þr       YOU ARE A        s¾üß
ÌÍ¾r                        süÝß
¼½Îr     TETRIS MASTERË     s¾¾¾
ÌÍÎr                        sÎÎw
ÜíÞr                        sÎÎÞ
¾üßr PLEASE ENTER YOUR NAME sÞÞ¾
wß¾r                        sÜíÎ
Þìýr !♡♡♡♡♡♡♡♡♡♡♡♡♡♡♡♡♡♡♡♡a s¾ÎÎ
ßÞ¾r b    NAME  SCORE  LV c sÎÞÞ
ÜÝýr +eeeeeeeeeeeeeeeeeeee: süßÜ
ÜÝír b 1                  c sÜzß
ìßÞr b                    c s¾ÞÜ
Î¼½r b 2                  c süÝß
ÞÌÍr b                    c s¼½Ü
ßìßr b 3                  c sÌÍÜ
Üý¾r deeeeeeeeeeeeeeeeeeeef s¾¼½
ÜÝýr                        sÎÌÍ
ÝÝßtuuuuuuuuuuuuuuuuuuuuuuuuvüß¾
¼½¼½ÜÝÝß¾¾¾ÜÝí¾Üzß¾¾ÜÝÝß¾ìß¼½¾ìý
ÌÍÌÍìßÜÝýÎüÝßÞwßÞÜywßÜíÜyÎ¾ÌÍÎÞ¾

"""

attributes = """
2222222222222222
2222222222222222
2222222222222222
2200333333330022
2200000000000022
2200000000000022
2200000000000022
2200000000000022
2200000000000022
2200000000000022
2200000000000022
2200000000000022
2200000000000022
2222222222222222
2222222222222222
0000000000000000"""

lengths = [32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32]  # fmt: skip

starting_addresses = [(32, 0), (32, 32), (32, 64), (32, 96), (32, 128), (32, 160), (32, 192),
 (32, 224), (33, 0), (33, 32), (33, 64), (33, 96), (33, 128), (33, 160),
 (33, 192), (33, 224), (34, 0), (34, 32), (34, 64), (34, 96), (34, 128),
 (34, 160), (34, 192), (34, 224), (35, 0), (35, 32), (35, 64), (35, 96),
 (35, 128), (35, 160), (35, 192), (35, 224)]  # fmt: skip


if __name__ == "__main__":
    try:
        nametable_builder.build_nametable(
            output,
            table,
            attributes,
            characters,
            original_sha1sum,
            lengths,
            starting_addresses,
        )
    except Exception as exc:
        print(f"Unable to build nametable: {type(exc).__name}: {exc!s}", file=sys.stderr)
        sys.exit(1)

