
import pathlib
import sys

import nametable_builder 

"""
This script has been generated by nametable_builder.py.  It's intended to rebuild the nametable
into a .bin

Unless modified, it will reproduce the original.  
"""

file = pathlib.Path(__file__)
output = file.parent / file.name.replace(".py", ".bin")

original_sha1sum = "36fa36fcab592f7b1b9373809ccbcdcbfd949e2b"

characters = (
    #0123456789ABCDEF
    "0123456789ABCDEF" #0
    "GHIJKLMNOPQRSTUV" #1
    "WXYZ-,'>!♡abcdef" #2
    "ghijklmnopqrstuv" #3
    "wxyz#$%&'()*+/:;" #4
    "<=?@[]^_`{|}~¹º»" #5
    "¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊË" #6
    "ÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛ" #7
    "ÜÝÞßàáâãäåæçèéêë" #8
    "ìíîïðñòóôõö÷øùúû" #9
    "üýþÿЉЊЋЌЍЎЏАБВГД" #A
    "ЕЖЗИЙКЛМНОПРСТУФ" #B
    "ХЦЧШЩЪЫЬЭЮЯабвгд" #C
    "εζηθικλμνξοπρςστ" #D
    "υφχψωϊϋόύώϏϐϑϒϓϔ" #E
    "ϕϖϗϘϙϚϛϜϝϞϟϠϡͰͱ " #F
)  # fmt: skip

table = """
ÖÃÓÓÎÕÖÔÑÖÃÓÔßÔßÓãÃÔÏãÌÍÃãÔÑÖÎÖÃ
ÎßãÓãÃÔÏãÎßãÔÕÕÖãÔàÖÞÖÜÝÞÕÖãÔßÔá
ãÎÖãÔàÖÞÖãÃoppppppppppqoppppppqã
ÃÓoppppppqÓr LINES-   sr      sÃ
Óãr -TYPEsÓtuuuuuuuuuuvrTOP   sÓ
ÜÖtuuuuuuvãghhhhhhhhhhir000000sÓ
ÔÕÕÖÃÌÍÃÔÕÏj          kr      sã
ÕÖÔÕßÜÝÞÕÖãj          krSCORE sÃ
Ïoppppppppqj          kr000000sÞ
ÓrÅÆÇÈÉÊË»sj          kr      sÃ
ãr        sj          ktuuuuuuvÓ
Ör wxy    sj          kÔÕÕÖÔÕÏÔß
Ör <=?000 sj          kghhhhiãÃÔ
Ör ()*    sj          kjNEXTkÎßÔ
Ãr {|}000 sj          kj    kãÎÖ
Ór %&     sj          kj    kÔßÌ
Ór ^_`000 sj          kj    kÎÖÜ
ãr ¼½     sj          kj    kÓÔÏ
Ír ¾¿ 000 sj          klmmmmnãÃÓ
Ýr z#$    sj          kopppppqÓã
Ör @[]000 sj          krLEVELsÓÔ
Ör +/:    sj          kr     sãÃ
Ãr ~¹º000 sj          ktuuuuuvÔá
ßr        sj          kÃÔÑÖÃÎÕÖã
Ïr ÀÁÂ000 sj          kÐÖãÔáãÃÔÕ
Ór        sj          kãÔÕÏãÎßÎÖ
ãtuuuuuuuuvlmmmmmmmmmmnÃÌÍãÃãÔßÃ
ÃÃÔÑÖÎÕÖÃÔÏÔÏÃÎÖÎÕÖÔÕÕÖÓÜÝÔáÃÔÕß
ÓÞÏãÃãÃÎßÃÞÖÓÓÓÃãÃÌÍÎÖÃÜÖÔÏãÓÔÕÕ
ÜÖãÔàÖÓãÔàÖÃãÓãÓÎßÜÝÓÃÞÕÖÃÓÔßÎÖÃ

"""

attributes = """
3333333333333333
3333333333333333
3333333333333333
3333332222233333
3333332222233333
3220032222233333
3220032222233333
3220032222233333
3220032222233333
3220032222233333
3220032222233333
3220032222233333
3220032222233333
3333333333333333
3333333333333333
0000000000000000"""

lengths = [32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32]  # fmt: skip

starting_addresses = [(32, 0), (32, 32), (32, 64), (32, 96), (32, 128), (32, 160), (32, 192),
 (32, 224), (33, 0), (33, 32), (33, 64), (33, 96), (33, 128), (33, 160),
 (33, 192), (33, 224), (34, 0), (34, 32), (34, 64), (34, 96), (34, 128),
 (34, 160), (34, 192), (34, 224), (35, 0), (35, 32), (35, 64), (35, 96),
 (35, 128), (35, 160), (35, 192), (35, 224)]  # fmt: skip


if __name__ == "__main__":
    try:
        nametable_builder.build_nametable(
            output,
            table,
            attributes,
            characters,
            original_sha1sum,
            lengths,
            starting_addresses,
        )
    except Exception as exc:
        print(f"Unable to build nametable: {type(exc).__name}: {exc!s}", file=sys.stderr)
        sys.exit(1)

