import pathlib
import sys
import subprocess
import nametable_builder

"""
This script has been generated by nametable_builder.py.  It's intended to rebuild the nametable
into a .bin

Unless modified, it will reproduce the original.  
"""

file = pathlib.Path(__file__)
output = file.parent / file.name.replace(".py", ".bin")

original_sha1sum = "a0d9fc35817a95bbeacfd66276a7a7e2217addf2"

characters = (
    #0123456789ABCDEF
    "0123456789ABCDEF" #0
    "GHIJKLMNOPQRSTUV" #1
    "WXYZ-,'╥┌━┐┇╏└╍┘" #2
    "ghijklmn╔╧╗╣╠╚╤╝" #3
    "wxyz╭▭╮╢╟╰▱╯├╪┤/" #4
    "┉=!@[]^Ë`{|}~¹()" #5
    "¼½¾¿ÀÁÂÃÄÅÆÇÈÉ‟." #6
    "ÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛ" #7
    "ÜÝÞßàáâãäåæçèéêë" #8
    "ìíîïðñòóôõö÷øùúû" #9
    "üýþÿЉЊЋЌЍЎЏАБВГД" #A
    "ЕЖЗИЙКЛМНОПРСТУФ" #B
    "ХЦЧШЩЪЫЬЭЮЯабвгд" #C
    "εζηθικλμνξοπρςστ" #D
    "υφχψωϊϋόύώϏϐϑϒϓϔ" #E
    "ϕϖϗϘϙ©ϛ┬ϝϞϟϠϡͰͱ_" #F
)  # fmt: skip

table = """
ÃÔÕÕÏÎÕÕÖÔÕÏÔÑÕÖÎÖÌÍÔÕÕÕÖÔÕÕÕÖÌÍ
ÐÖÌÍããÔÕÕÕÖÞÖãÔÕßÔàÝÔÏghhhhhhiðÝ
ÓÃðÝÃÔÏ╔╧╧╧╧╧╧╧╧╧╧╗ÎÖÓj_NEXT_kãÃ
ãÓãÔͰÖÓ╣_LINES-___╠ÓÔßj______kÎß
ÔàÖÃãÔß╚╤╤╤╤╤╤╤╤╤╤╝ÞÖÃj______kÓÃ
ÎÖÎßÃghhhhhhhhhhhhhhiÓj______kãÓ
ÓÔßÔáj______________kÓj______kÎß
ÞÖÎÖÓj______________kÓj______kãÃ
ÔÕßÃãj______________kãlmmmmmmnÃÓ
ÃÔÕáÃj______________kÎÕÖÔÕÕÕÖÔáÓ
ÞÑÖãÓj______________kÓ╔╧╧╧╧╧╧╗ÓÓ
ÃãÔÕßj______________kã╣______╠ãã
ÐÕÖÎÖj______________kÃ╣TOP___╠ÌÍ
ãÔÕßÃj______________kÓ╣000000╠ðÝ
ÌÍÎÖÓj______________kÓ╣______╠ãÃ
ðÝÓÃÓj______________kÓ╣SCORE_╠Ôá
ãÔßÓÓj______________kã╣000000╠ÃÓ
ÎÕÖÓãj______________kÃ╣______╠Óã
ÓÔÏÞÖj______________kÓ╚╤╤╤╤╤╤╝ÞÏ
ãÃÞÕÖj______________kÐÖÔÕÕÕÖÔÕÏã
ÔàÕÖÃj______________kã╔╧╧╧╧╧╧╗ÓÃ
ÔÑÖÎßj______________kÃ╣LEVEL_╠ãÓ
ÃÓÔßÃj______________kÓ╣______╠Ôá
ÓãÔÑßj______________kÓ╚╤╤╤╤╤╤╝Ãã
ÞÕÖãÃj______________kÞÖÔÕÕÕÖÔÕáÃ
ÎÖÎÕßj______________kÃ╔╧╧╧╧╧╧╗ãÓ
ÓÃãÃÃj______________kÓ╣_-TYPE╠Îß
ÓÞÕßÓj______________kÓ╚╤╤╤╤╤╤╝ãÃ
ãÃÔÕßlmmmmmmmmmmmmmmnÞÖÃÔÕÏÔÑÕÖÓ
ÔàÕÖÔÕÕÕÖÔÕÕÏÔÕÕÕÕÎÕÕÖÔàÕÖÞÖãÔÕß

"""

attributes = """
3333333333333333
3333333333333333
3333333333333333
3332222222333333
3332222222333333
3332222222333333
3332222222333333
3332222222333333
3332222222333333
3332222222333333
3332222222333333
3332222222333333
3332222222333333
3332222222333333
3333333333333333
0000000000000000"""

lengths = [32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32]  # fmt: skip

starting_addresses = [(32, 0), (32, 32), (32, 64), (32, 96), (32, 128), (32, 160), (32, 192),
 (32, 224), (33, 0), (33, 32), (33, 64), (33, 96), (33, 128), (33, 160),
 (33, 192), (33, 224), (34, 0), (34, 32), (34, 64), (34, 96), (34, 128),
 (34, 160), (34, 192), (34, 224), (35, 0), (35, 32), (35, 64), (35, 96),
 (35, 128), (35, 160), (35, 192), (35, 224)]  # fmt: skip


if __name__ == "__main__":
    try:
        raw_output = file.parent / output.name.replace(".bin", ".raw")
        nametable_builder.build_nametable(
            raw_output,
            table,
            attributes,
            characters,
            original_sha1sum,
            lengths,
            starting_addresses,
        )
        subprocess.run(["node", str(file.parent / "compress.js"), raw_output, output])
        raw_output.unlink()
    except Exception as exc:
        print(
            f"Unable to build nametable: {type(exc).__name__}: {exc!s}", file=sys.stderr
        )
        sys.exit(1)
