
import pathlib
import sys

import nametable_builder 

"""
This script has been generated by nametable_builder.py.  It's intended to rebuild the nametable
into a .bin

Unless modified, it will reproduce the original.  
"""

file = pathlib.Path(__file__)
output = file.parent / file.name.replace(".py", ".bin")

original_sha1sum = "ea1a97c4553ec3d43de5476fbe28a50cd7ad61ce"

characters = (
    #0123456789ABCDEF
    "0123456789ABCDEF" #0
    "GHIJKLMNOPQRSTUV" #1
    "WXYZ-,'>!♡abcdef" #2
    "ghijklmnopqrstuv" #3
    "wxyz#$%&'()*+/:;" #4
    "<=?@[]^_`{|}~¹º»" #5
    "¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊË" #6
    "ÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛ" #7
    "ÜÝÞßàáâãäåæçèéêë" #8
    "ìíîïðñòóôõö÷øùúû" #9
    "üýþÿЉЊЋЌЍЎЏАБВГД" #A
    "ЕЖЗИЙКЛМНОПРСТУФ" #B
    "ХЦЧШЩЪЫЬЭЮЯабвгд" #C
    "εζηθικλμνξοπρςστ" #D
    "υφχψωϊϋόύώϏϐϑϒϓϔ" #E
    "ϕϖϗϘϙϚϛϜϝϞϟϠϡͰͱ " #F
)  # fmt: skip

table = """
¼½¼½¾Þ¾ìß¾¾¾ÞÜíÜíÌÍ¾ÞÜÝÝßìß¾¾ÜÝí
ÌÍÌÍÎÜyÎìýÎüÝßüßüßÜxßìÝßÜýìýüÝßÞ
ÜÝÝßüßÞÞÞÜýoppppppppqÞÜÝÝßÞÜÝí¼½
Üí¾opppppppr B-TYPE spppppppqÞÌÍ
¾ÎÎr       tuuuuuuuuv       sìÝß
ÎÞÎr                        sÞÜí
üßÞr                        s¼½Î
ìÝßr    #$$$$$%    #$$$$$$% sÌÍÞ
ÞÜír    &LEVEL'    &HEIGHT' sÜÝí
¼½Îr    ()))))*    ())))))* s¾¾Þ
ÌÍÞr  !♡<♡<♡<♡<♡a  !♡<♡<♡a  sÎüí
ÜÝír  b0b1b2b3b4c  b0b1b2c  sÎ¾Þ
¾¾Þr  +e/e/e/e/e:  +e/e/e:  sÞÎÜ
Îüír  b5b6b7b8b9c  b3b4b5c  s¾üß
Î¾Þr  de=e=e=e=ef  de=e=ef  süÝß
ÞÎÜr                        sìÝß
¾üßr                        sÞÜí
üÝßr !♡♡♡♡♡♡♡♡♡♡♡♡♡♡♡♡♡♡♡♡a s¼½Î
¾Üír b    NAME  SCORE  LV c sÌÍÞ
y¾Îr +eeeeeeeeeeeeeeeeeeee: sÜÝí
ÞÎÞr b 1                  c s¾¾Þ
Üý¾r b                    c sÎüí
¼½Îr b 2                  c sÎ¾Þ
ÌÍÎr b                    c sÞÎÜ
¾¾Þr b 3                  c s¾üß
ÎwÏr deeeeeeeeeeeeeeeeeeeef süÝß
ÎÞ¾r                        s¾¼½
ÞìýtuuuuuuuuuuuuuuuuuuuuuuuuvÎÌÍ
¾Þìß¾ÜÝíÜÝÝßìßìß¼½ìÝß¾ÜzßÜíÜíüß¾
ÎÜýÜxß¾ÞÜzßÜý¾Î¾ÌÍÞÜÝý¾Þ¼½üßüßÜx

"""

attributes = """
2222222222222222
2222222222222222
2211122222211122
2211222212222222
2211222202222222
2213333333333122
2213333333333122
2213333333333122
2200000000000022
2200000000000022
2200000000000022
2200000000000022
2200000000000022
2222222222222222
2222222222222222
0000000000000000"""

lengths = [32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32]  # fmt: skip

starting_addresses = [(32, 0), (32, 32), (32, 64), (32, 96), (32, 128), (32, 160), (32, 192),
 (32, 224), (33, 0), (33, 32), (33, 64), (33, 96), (33, 128), (33, 160),
 (33, 192), (33, 224), (34, 0), (34, 32), (34, 64), (34, 96), (34, 128),
 (34, 160), (34, 192), (34, 224), (35, 0), (35, 32), (35, 64), (35, 96),
 (35, 128), (35, 160), (35, 192), (35, 224)]  # fmt: skip


if __name__ == "__main__":
    try:
        nametable_builder.build_nametable(
            output,
            table,
            attributes,
            characters,
            original_sha1sum,
            lengths,
            starting_addresses,
        )
    except Exception as exc:
        print(f"Unable to build nametable: {type(exc).__name}: {exc!s}", file=sys.stderr)
        sys.exit(1)

